#!/bin/bash
set -e
set -o pipefail
set -u

echo "Current directory:"
pwd

echo "Contents:"
ls

FILE=.gi/index.lock
if [ -f "$FILE" ]; then
    echo "Found $FILE - deleting"
    rm -f $FILE
else
    echo "$FILE not found"
fi
