#!/bin/bash
set -e
set -o pipefail
set -u

echo "Current directory:"
pwd

echo "Contents:"
ls -a

FILE=.git/index.lock
if [ -f "$FILE" ]; then
    echo "$FILE exists - deleting"
    rm -f $FILE
else
    echo "$FILE does not exist"
fi
